name: Validate Server Manifests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv with caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync

      - name: Validate Manifest JSON Files
        run: |
          python scripts/validate_manifest.py
