name: Validate Server Manifests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Manifest JSON Files
        uses: walbo/validate-json@v1.1.0
        with:
          # Validate all manifest.json files in the servers directory
          files: mcp-registry/servers/*/manifest.json
          # Use our schema file
          schema: mcp-registry/schema/manifest-schema.json
          # Use draft-07 as specified in our schema
          schema-version: draft-07
          # Print information about valid files too
          print-valid-files: true
